### ISSUE TITLE
Cog predict fails with semaphore leak warning and invalid media type error

### ISSUE THREAD

**Issue by ghost** [lucataco/cog-flux-dev-multi-lora#2]
When running `cog predict` with the Flux txt2img pipeline, the prediction completes but fails to write the output due to two errors:

1. A warning about leaked semaphore objects
2. An error decoding the dataurl due to an invalid character for media type

### Steps to Reproduce

1. Set up the Flux txt2img pipeline in a Cog project
2. Run the following command:

```bash
cog predict -i prompt="a photo of TOK, sftsrv style" -i extra_loras=["lucataco/flux-queso","https://huggingface.co/alvdansen/softserve_anime/resolve/main/flux_dev_softstyle_araminta_k.safetensors"]
```

### Expected Behavior

The prediction should complete and output the generated image without any errors.

### Actual Behavior

The prediction completes, but fails to write the output with the following errors:

1. Semaphore leak warning:
```
/root/.pyenv/versions/3.11.10/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

2. Invalid media type error:
```
ⅹ Failed to write output 0: Failed to decode dataurl: invalid character for media type
```

### Additional Context

The prediction process itself seems to complete successfully, as indicated by the progress bar reaching 100%. The issue appears to be related to writing the output or encoding the generated image.

### Possible Solutions

1. Investigate the semaphore leak in the multiprocessing module
2. Check the encoding of the output image and ensure it's compatible with the expected media type
3. Verify that the Flux txt2img pipeline is correctly configured to output images in a format that Cog can handle

Any assistance in resolving these issues would be greatly appreciated.

**Comment by lucataco** [comment]
By default the model returns an image in webp format, change the `output_format` to anything else
