### ISSUE TITLE
Fast FLUX

### ISSUE THREAD

**Issue by gregorym** [lucataco/cog-flux-dev-multi-lora#3]
Hi @lucataco,

Is it possible to include the Flux optimization explained in your blog https://replicate.com/blog/flux-is-fast-and-open-source into this cog?

Thanks!

**Comment by lucataco** [comment]
Work in progress!

**Comment by gregorym** [comment]
> Work in progress!

Do you have an ETA?

**Comment by gregorym** [comment]
Any update on this given your improvements? https://replicate.com/blog/fast-flux-fine-tunes
